export enum ActionType {
  GET_ACCOUNTS = "GET_ACCOUNTS",
  GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS",
  GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_FAILURE",

  GET_CURRENT_ACCOUNT = "GET_CURRENT_ACCOUNT",
  GET_CURRENT_ACCOUNT_SUCCESS = "GET_CURRENT_ACCOUNT_SUCCESS",
  GET_CURRENT_ACCOUNT_FAILURE = "GET_CURRENT_ACCOUNT_FAILURE",
}
